### ISSUE TITLE
Diversity and Inclusion Page

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024#73]
[Needs content](https://github.com/pythonindia/inpycon2024/blob/main/src/diversity-inclusion.md)

**Comment by vellankikoti** [comment]
### PyCon India 2024: Fostering Diversity and Inclusion

This page will be regularly updated with new information and resources. We invite you to visit it frequently to stay updated on our accessibility initiatives.

PyCon India 2024 is not just a conference; it's a community where every voice is valued and celebrated. We believe that diversity and inclusion are fundamental pillars that make the Python community vibrant, innovative, and welcoming. Our goal for PyCon India 2024 is to create a space where everyone, regardless of their background, has the opportunity to learn, share, and grow in a supportive environment.

#### Why Diversity and Inclusion Matter at PyCon India

The strength of the Python community lies in its diversity. We recognize that diverse perspectives bring unique insights and creativity, driving innovation and problem-solving. By fostering an inclusive culture, we aim to provide an equitable platform where everyone feels comfortable, empowered, and valued.

At PyCon India 2024, we are committed to creating an environment that encourages participation from people of all races, ethnicities, genders, sexual orientations, abilities, socioeconomic statuses, religions, and cultures. This is not just about compliance but about building a thriving community where every individual has the chance to contribute and benefit.

#### Our Initiatives to Promote Diversity and Inclusion

To ensure that PyCon India 2024 is a welcoming experience for all, we are implementing several initiatives:

1. **Diversity Scholarships:** We will provide scholarships to individuals from underrepresented groups who might otherwise face financial barriers to attending PyCon India. This includes support for conference registration, travel, and accommodation for the students and others.
https://in.pycon.org/2024/scholarship/

2. **Accessible Venue:** We have chosen a venue that is accessible for all, including those with mobility impairments. We are committed to making PyCon India 2024 a comfortable and enjoyable experience for everyone.
https://in.pycon.org/2024/bengaluru/

3. **Inclusive Content:** Our speaker lineup will reflect a wide range of perspectives and expertise. We encourage talk proposals from individuals across all experience levels and backgrounds, ensuring a diverse set of topics that cater to the interests of our community.

4. **Safe and Supportive Environment:** PyCon India 2024 will adhere to a strict Code of Conduct that promotes a safe, inclusive, and harassment-free conference experience for everyone. Our dedicated team will be on hand to provide support and address any concerns during the event.
https://in.pycon.org/2024/code-of-conduct/
https://in.pycon.org/2024/health-safety-guidelines/

5. **Networking Opportunities:** We will host various networking events and sessions designed to facilitate interactions among attendees from different backgrounds. These activities will help build lasting connections, share knowledge, and celebrate the diversity that makes the Python community so special.

6. **Child Care:** We understand that one of the challenges parents face while attending conferences is arranging child care. PyCon India 2024 is providing an on-site child care service to support parents and guardians. This initiative ensures that parents can fully participate in the conference activities, knowing their children are safe, engaged, and well cared for. https://in.pycon.org/2024/childcare/

7. **PyLadies Lunch at PyCon India 2024:** We are happy to host the PyLadies Lunch at PyCon India 2024, a special event for women and gender minorities in the Python community. This lunch is a chance to meet, share experiences, and connect in a friendly setting. It is a great way to find support, learn from others, and talk about topics that matter to you. We invite all women and gender minorities at PyCon India 2024 to join us and be part of a community that values diversity and inclusion in tech.



#### How You Can Get Involved

Your participation and support are crucial in making PyCon India 2024 a truly inclusive event. Here are some ways you can get involved:
**Become a Mentor:** Share your knowledge and experience with others by becoming a mentor. This program is designed to support all members of our community, whether they're speaking or submitting a workshop for the first time or are seasoned speakers looking for feedback. Through this mentorship initiative, mentors can review slides, provide tips on presenting, and help guide participants to deliver successful talks and workshops at PyCon India 2024. 

We usually reach out to industry professionals and experts who have delivered multiple talks and workshops at various conferences, covering all the proposal categories mentioned in our Call for Proposals (CFP). These categories include Python in Platform Engineering, Artificial Intelligence and Machine Learning, Python on Hardware, Community, Core Python, Python in Education and Research, Python in Web and Applications, and more. Based on these categories, we identify suitable mentors and schedule sessions to support speakers who need guidance.

If you're interested in becoming a mentor in the future, you can reach out to us by filling out the mentorship form with your experience and details. Our mentorship team reviews these applications and onboards individuals who can contribute to building a supportive learning environment for our community. This process helps ensure that each speaker has the tools and confidence needed to make their presentations a success.

**Volunteers:** Help us make PyCon India 2024 an event where everyone feels welcome and included. Volunteering is a great way to give back to the community and make a positive impact.

Spread the Word: Help us reach a wider audience by sharing information about PyCon India 2024 and our diversity and inclusion initiatives within your networks.

#### Join Us in Building an Inclusive Python Community

We invite you to be a part of PyCon India 2024, where diversity is celebrated, and inclusion is at the heart of our mission. Together, we can create a welcoming and enriching environment where everyone feels empowered to contribute, learn, and grow.

Let's make PyCon India 2024 a memorable and inspiring experience for all. Join us in building a community that truly reflects the diverse world we live in. 

For more details about our diversity and inclusion initiatives or to apply for scholarships, visit [PyCon India 2024](https://in.pycon.org/2024/). Let's create a space where every Pythonista can thrive!

**Comment by vellankikoti** [comment]
@palnabarun @anistark can any one of you do a final review then we will proceed with the deployment.

**Comment by SaptakS** [comment]
@vellankikoti I don't see a PR for this. Do you want me to create a PR to add this content?

**Comment by anistark** [comment]
@vellankikoti Open PR please. It's easier to add comments.

**Comment by vellankikoti** [comment]
https://github.com/pythonindia/inpycon2024/pull/104
@SaptakS @anistark
