### ISSUE TITLE
Add Reviewers and Mentors Page

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024#98]
Reviewers and Mentors details to be taken from @bhavin192

**Comment by SaptakS** [comment]
This is a content issue that can be edited in the `data/` folder. Doesn't need any development if I am correct.

**Comment by anistark** [comment]
> This is a content issue that can be edited in the `data/` folder. Doesn't need any development if I am correct.

Would need another section to be added. But mostly data yes.
This would come under Team section.

**Comment by SaptakS** [comment]
@anistark So below the team, you want another section titles "Reviewers and Mentors" ?

**Comment by bhavin192** [comment]
Yes, something like that would work. 
But then we need to have some sort of navigation at top, otherwise I feel we are not recognizing them enough? The current volunteer list is huge enough for someone to not scroll till the end to see reviewers and mentors :smile: 

Good to have: I was thinking if mentors and reviewers can have a page like speakers? Or maybe my idea is based on what we did back in 2020: https://in.pycon.org/blog/2020/thank-you-reviewers.html As in the current about us page doesn't give more details about a person. 
But this can be done later as well.

**Comment by SaptakS** [comment]
> The current volunteer list is huge enough for someone to not scroll till the end to see reviewers and mentors

True. I was thinking I can make them collapsable, but don't feel like the design will look good. We can definitely add another item in navigation and point it to the anchor in the same page or to a separate page. So let me know if you think a separate page will be better, and I can do that.

**Comment by SaptakS** [comment]
Probably should not close this till the content is added.

**Comment by anistark** [comment]
Bhavin can add it as separate one?

It's not breaking anything anyway.

**Comment by anistark** [comment]
It was closed by the PR merged automatically tho 😅

**Comment by anistark** [comment]
This was done.
